apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-ai-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-ai-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "k8s-ai-operator.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
